<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LicensesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $licenses = [
            // Microsoft Office Licenses
            [
                'license_name' => 'Microsoft Office 365 Business Premium',
                'product_key' => 'OFF365-BP-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addYear(),
                'licensed_email' => 'it-department@company.com',
                'licensed_name' => 'IT Department',
                'manufacturer' => 'Microsoft',
                'min_qty' => 5,
                'total_qty' => 50,
                'available_qty' => 35,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Microsoft Office 2021 Professional',
                'product_key' => 'OFF2021-PRO-'.strtoupper(uniqid()),
                'expiration_date' => null,
                'licensed_email' => 'licenses@company.com',
                'licensed_name' => 'Company Wide',
                'manufacturer' => 'Microsoft',
                'min_qty' => 10,
                'total_qty' => 100,
                'available_qty' => 42,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Microsoft Windows 11 Pro',
                'product_key' => 'WIN11-PRO-'.strtoupper(uniqid()),
                'expiration_date' => null,
                'licensed_email' => 'it-admin@company.com',
                'licensed_name' => 'IT Administration',
                'manufacturer' => 'Microsoft',
                'min_qty' => 5,
                'total_qty' => 75,
                'available_qty' => 28,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Adobe Creative Cloud
            [
                'license_name' => 'Adobe Creative Cloud All Apps',
                'product_key' => 'ADOBE-CC-ALL-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(6),
                'licensed_email' => 'design-team@company.com',
                'licensed_name' => 'Design Team',
                'manufacturer' => 'Adobe',
                'min_qty' => 3,
                'total_qty' => 15,
                'available_qty' => 8,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Adobe Photoshop CC',
                'product_key' => 'ADOBE-PS-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addYear(),
                'licensed_email' => 'graphics@company.com',
                'licensed_name' => 'Graphics Department',
                'manufacturer' => 'Adobe',
                'min_qty' => 2,
                'total_qty' => 10,
                'available_qty' => 6,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Adobe Acrobat Pro DC',
                'product_key' => 'ADOBE-ACROBAT-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(9),
                'licensed_email' => 'admin@company.com',
                'licensed_name' => 'Administration',
                'manufacturer' => 'Adobe',
                'min_qty' => 5,
                'total_qty' => 25,
                'available_qty' => 12,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Antivirus & Security
            [
                'license_name' => 'Norton 360 Business',
                'product_key' => 'NORTON-360-BIZ-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(8),
                'licensed_email' => 'security@company.com',
                'licensed_name' => 'Security Team',
                'manufacturer' => 'Norton',
                'min_qty' => 10,
                'total_qty' => 80,
                'available_qty' => 45,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'McAfee Endpoint Security',
                'product_key' => 'MCAFEE-ENDPOINT-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addYear(),
                'licensed_email' => 'it-security@company.com',
                'licensed_name' => 'IT Security',
                'manufacturer' => 'McAfee',
                'min_qty' => 5,
                'total_qty' => 60,
                'available_qty' => 32,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Kaspersky Small Office',
                'product_key' => 'KASPERSKY-SO-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(11),
                'licensed_email' => 'support@company.com',
                'licensed_name' => 'Support Team',
                'manufacturer' => 'Kaspersky',
                'min_qty' => 3,
                'total_qty' => 20,
                'available_qty' => 15,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Development Tools
            [
                'license_name' => 'JetBrains PhpStorm',
                'product_key' => 'JETBRAINS-PHP-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addYear(),
                'licensed_email' => 'dev-team@company.com',
                'licensed_name' => 'Development Team',
                'manufacturer' => 'JetBrains',
                'min_qty' => 3,
                'total_qty' => 12,
                'available_qty' => 7,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Visual Studio Professional',
                'product_key' => 'VS-PRO-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(6),
                'licensed_email' => 'developers@company.com',
                'licensed_name' => 'Software Developers',
                'manufacturer' => 'Microsoft',
                'min_qty' => 2,
                'total_qty' => 8,
                'available_qty' => 5,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Sublime Text License',
                'product_key' => 'SUBLIME-TEXT-'.strtoupper(uniqid()),
                'expiration_date' => null,
                'licensed_email' => 'web-dev@company.com',
                'licensed_name' => 'Web Development',
                'manufacturer' => 'Sublime HQ',
                'min_qty' => 1,
                'total_qty' => 5,
                'available_qty' => 3,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Design & Media
            [
                'license_name' => 'CorelDRAW Graphics Suite',
                'product_key' => 'COREL-DRAW-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(18),
                'licensed_email' => 'design@company.com',
                'licensed_name' => 'Design Department',
                'manufacturer' => 'Corel',
                'min_qty' => 2,
                'total_qty' => 6,
                'available_qty' => 4,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Final Cut Pro',
                'product_key' => 'FINAL-CUT-PRO-'.strtoupper(uniqid()),
                'expiration_date' => null,
                'licensed_email' => 'video-team@company.com',
                'licensed_name' => 'Video Production',
                'manufacturer' => 'Apple',
                'min_qty' => 1,
                'total_qty' => 3,
                'available_qty' => 2,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Sketch Professional',
                'product_key' => 'SKETCH-PRO-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addYear(),
                'licensed_email' => 'ui-ux@company.com',
                'licensed_name' => 'UI/UX Team',
                'manufacturer' => 'Sketch',
                'min_qty' => 2,
                'total_qty' => 8,
                'available_qty' => 5,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Business & Productivity
            [
                'license_name' => 'QuickBooks Enterprise',
                'product_key' => 'QUICKBOOKS-ENT-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(15),
                'licensed_email' => 'accounting@company.com',
                'licensed_name' => 'Accounting Department',
                'manufacturer' => 'Intuit',
                'min_qty' => 3,
                'total_qty' => 10,
                'available_qty' => 6,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Sage 50cloud Accounting',
                'product_key' => 'SAGE-50CLOUD-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addYear(),
                'licensed_email' => 'finance@company.com',
                'licensed_name' => 'Finance Team',
                'manufacturer' => 'Sage',
                'min_qty' => 2,
                'total_qty' => 5,
                'available_qty' => 3,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'AutoCAD 2024',
                'product_key' => 'AUTOCAD-2024-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->addMonths(12),
                'licensed_email' => 'engineering@company.com',
                'licensed_name' => 'Engineering Department',
                'manufacturer' => 'Autodesk',
                'min_qty' => 2,
                'total_qty' => 8,
                'available_qty' => 5,
                'status' => true,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Expired or Inactive Licenses (for testing)
            [
                'license_name' => 'Windows 10 Pro (Expired)',
                'product_key' => 'WIN10-PRO-EXP-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->subMonths(3),
                'licensed_email' => 'old-licenses@company.com',
                'licensed_name' => 'Legacy Systems',
                'manufacturer' => 'Microsoft',
                'min_qty' => 5,
                'total_qty' => 20,
                'available_qty' => 0,
                'status' => false,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'license_name' => 'Adobe Illustrator CS6',
                'product_key' => 'ADOBE-AI-CS6-'.strtoupper(uniqid()),
                'expiration_date' => Carbon::now()->subYear(),
                'licensed_email' => 'archive@company.com',
                'licensed_name' => 'Archived Software',
                'manufacturer' => 'Adobe',
                'min_qty' => 1,
                'total_qty' => 5,
                'available_qty' => 0,
                'status' => false,
                'updated_by' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert all licenses
        DB::table('licenses')->insert($licenses);

        $this->command->info('Successfully seeded 20 software licenses for office use.');
    }
}
