<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\ModelType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModelTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        ModelType::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $this->command->info('Starting model type seeding...');

        // Get category IDs
        $categories = Category::all()->keyBy('name');

        $models = [
            // Air Conditioner Models
            [
                'name' => 'York 2.0 HP',
                'description' => 'Air conditioner York 2.0 hp',
                'category_id' => $categories['Air Conditioners']->id,
                'brand' => 'York',
                'model_number' => '2.0HP',
                'specifications' => [
                    'type' => 'Split Unit',
                    'capacity' => '2.0 HP',
                    'voltage' => '240V',
                    'features' => ['Remote Control', 'Timer', 'Sleep Mode'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Cassette Type 2.5 HP',
                'description' => 'Air conditioner (Cassette Type) 2.5 hp',
                'category_id' => $categories['Air Conditioners']->id,
                'brand' => 'Generic',
                'model_number' => 'CASSETTE-2.5HP',
                'specifications' => [
                    'type' => 'Cassette',
                    'capacity' => '2.5 HP',
                    'voltage' => '240V',
                    'features' => ['Ceiling Mount', '4-Way Airflow'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Daikin Cassette 2.5 HP',
                'description' => 'Air conditioner Daikin (Cassette Type) 2.5 hp',
                'category_id' => $categories['Air Conditioners']->id,
                'brand' => 'Daikin',
                'model_number' => 'CASSETTE-2.5HP-DAIKIN',
                'specifications' => [
                    'type' => 'Cassette',
                    'capacity' => '2.5 HP',
                    'voltage' => '240V',
                    'features' => ['Inverter Technology', 'Quiet Operation'],
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Cassette Type 2.0 HP',
                'description' => 'Air conditioner (Cassette Type) 2.0 hp',
                'category_id' => $categories['Air Conditioners']->id,
                'brand' => 'Generic',
                'model_number' => 'CASSETTE-2.0HP',
                'specifications' => [
                    'type' => 'Cassette',
                    'capacity' => '2.0 HP',
                    'voltage' => '240V',
                    'features' => ['Ceiling Mount', '4-Way Airflow'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Cassette Type 1.0 HP',
                'description' => 'Install 1hp, Cassette & Outdoor',
                'category_id' => $categories['Air Conditioners']->id,
                'brand' => 'Generic',
                'model_number' => 'CASSETTE-1.0HP',
                'specifications' => [
                    'type' => 'Cassette',
                    'capacity' => '1.0 HP',
                    'voltage' => '240V',
                    'features' => ['Ceiling Mount', 'Energy Efficient'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 5,
            ],

            // Computer Models
            [
                'name' => 'Dell Optiplex 5050',
                'description' => 'Desktop Dell Optiplex 5050',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => 'Optiplex 5050',
                'specifications' => [
                    'processor' => 'Intel Core i5',
                    'ram' => '8GB DDR4',
                    'storage' => '256GB SSD',
                    'graphics' => 'Integrated Intel HD',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Dell OptiPlex 3050 Mini Tower',
                'description' => 'Desktop Dell OptiPlex 3050 Mini Tower CTO',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => 'OptiPlex 3050',
                'specifications' => [
                    'processor' => 'Intel Core i3',
                    'ram' => '4GB DDR4',
                    'storage' => '500GB HDD',
                    'graphics' => 'Integrated Intel HD',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 7,
            ],
            // Add this missing model for computers 76-78
            [
                'name' => 'Dell OptiPlex 3060 Mini Tower',
                'description' => 'Desktop Dell OptiPlex 3060 Mini Tower CTO',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => 'OptiPlex 3060',
                'specifications' => [
                    'processor' => 'Intel Core i5',
                    'ram' => '8GB DDR4',
                    'storage' => '256GB SSD',
                    'graphics' => 'Integrated Intel UHD',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Dell Pro Tower QCT1250',
                'description' => 'Dell Pro Tower QCT1250',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => 'QCT1250',
                'specifications' => [
                    'processor' => 'Intel Xeon',
                    'ram' => '16GB DDR4',
                    'storage' => '1TB SSD',
                    'graphics' => 'Professional Graphics Card',
                    'type' => 'Server/Workstation Tower',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Lenovo ThinkPad L420',
                'description' => 'Lenovo ThinkPad L420 Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Lenovo',
                'model_number' => 'L420',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'ThinkPad',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Dell Vostro 5471',
                'description' => 'Dell Vostro 5471 Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '5471',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Vostro',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Dell Latitude 3490 CTO',
                'description' => 'Dell Latitude 3490 CTO Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3490 CTO',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Dell Latitude 3400 BTX',
                'description' => 'Dell Latitude 3400 BTX Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3400 BTX',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Dell Latitude 3400 CTO',
                'description' => 'Dell Latitude 3400 CTO Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3400 CTO',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Dell Latitude 3410 CTO',
                'description' => 'Dell Latitude 3410 CTO Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3410 CTO',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Dell Latitude 3510 CTO',
                'description' => 'Dell Latitude 3510 CTO Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3510 CTO',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Apple iPad Pro 11',
                'description' => 'Apple iPad Pro 11 WIFI 256GB',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Apple',
                'model_number' => 'AA230',
                'specifications' => [
                    'type' => 'Tablet',
                    'storage' => '256GB',
                    'connectivity' => 'WIFI',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Dell Latitude 3420',
                'description' => 'Dell Latitude 3420 Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3420',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 48,
                'status' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Dell Latitude 3520',
                'description' => 'Dell Latitude 3520 Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3520',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Dell Latitude 3540',
                'description' => 'Dell Latitude 3540 Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3540',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Dell Latitude 3540 XCTO',
                'description' => 'Dell Latitude 3540 XCTO Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3540 XCTO',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Dell Latitude 3550 XCTO',
                'description' => 'Dell Latitude 3550 XCTO Notebook',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => '3550 XCTO',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Latitude',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Dell Pro 14 (PC14250) XCTO Base',
                'description' => 'Dell Pro 14 Notebook (PC14250) XCTO Base',
                'category_id' => $categories['Computers']->id,
                'brand' => 'Dell',
                'model_number' => 'PC14250 XCTO',
                'specifications' => [
                    'type' => 'Notebook',
                    'series' => 'Pro 14',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 23,
            ],
            // Printer Models
            [
                'name' => 'HP LaserJet Printer M401DN',
                'description' => 'HP LaserJet Printer M401DN',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => 'M401DN',
                'specifications' => [
                    'type' => 'Laser Printer',
                    'print_technology' => 'Laser',
                    'functions' => 'Print',
                    'connectivity' => 'Ethernet, USB',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'HP LaserJet Printer M425DN',
                'description' => 'HP LaserJet Printer M425DN',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => 'M425DN',
                'specifications' => [
                    'type' => 'Laser Printer',
                    'print_technology' => 'Laser',
                    'functions' => 'Print, Copy, Scan, Fax',
                    'connectivity' => 'Ethernet, USB',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'HP LaserJet Enterprise P3015DN',
                'description' => 'HP LaserJet Enterprise P3015DN',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => 'P3015DN',
                'specifications' => [
                    'type' => 'Laser Printer',
                    'print_technology' => 'Laser',
                    'functions' => 'Print',
                    'connectivity' => 'Ethernet, USB',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'HP LaserJet Pro 400 Printer M401DN',
                'description' => 'HP LaserJet Pro 400 Printer M401DN',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => 'M401DN',
                'specifications' => [
                    'type' => 'Laser Printer',
                    'print_technology' => 'Laser',
                    'functions' => 'Print',
                    'connectivity' => 'Ethernet, USB',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'HP LaserJet P2035',
                'description' => 'HP LaserJet P2035 Printer',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => 'P2035',
                'specifications' => [
                    'type' => 'Laser Printer',
                    'print_technology' => 'Laser',
                    'functions' => 'Print',
                    'connectivity' => 'USB',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'HP LaserJet Printer M402DN',
                'description' => 'HP LaserJet Printer Model M402DN',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => 'M402DN',
                'specifications' => [
                    'type' => 'Laser Printer',
                    'print_technology' => 'Laser',
                    'functions' => 'Print',
                    'connectivity' => 'Ethernet, USB',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'HP LaserJet MFP 477FDW',
                'description' => 'HP LaserJet Printer Model MFP 477FDW',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => '477FDW',
                'specifications' => [
                    'type' => 'Multifunction Printer',
                    'print_technology' => 'Laser',
                    'functions' => 'Print, Copy, Scan, Fax',
                    'connectivity' => 'Ethernet, USB, Wireless',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 30,
            ],
            // Scanner Model
            [
                'name' => 'HP Scanner G3110',
                'description' => 'HP Scanner G3110',
                'category_id' => $categories['Printers & Scanners']->id,
                'brand' => 'HP',
                'model_number' => 'G3110',
                'specifications' => [
                    'type' => 'Flatbed Scanner',
                    'scan_technology' => 'CIS',
                    'maximum_resolution' => '1200 dpi',
                    'connectivity' => 'USB',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 31,
            ],
            // Server Models
            [
                'name' => 'QNAP Storage Server 6TB',
                'description' => 'QNAP Storage Server 6TB - Additional Back-up for MFund MCY',
                'category_id' => $categories['Servers']->id,
                'brand' => 'QNAP',
                'model_number' => 'Storage-6TB',
                'specifications' => [
                    'type' => 'Storage Server',
                    'storage_capacity' => '6TB',
                    'purpose' => 'Backup for MFund MCY',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Dell PowerEdge R550',
                'description' => 'Dell PowerEdge R550 - Physical server for Swift Integration Layer support',
                'category_id' => $categories['Servers']->id,
                'brand' => 'Dell',
                'model_number' => 'PowerEdge R550',
                'specifications' => [
                    'type' => 'Rack Server',
                    'form_factor' => '2U',
                    'purpose' => 'Swift Integration Layer support',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'VPN Box for SWIFT SC',
                'description' => 'SIPN Connectivity - VPN Box for SWIFT SC',
                'category_id' => $categories['Servers']->id,
                'brand' => 'AMTB',
                'model_number' => 'AMTBMYKL-SWIFT-SC',
                'specifications' => [
                    'type' => 'VPN Gateway',
                    'purpose' => 'SIPN Connectivity for SWIFT',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Windows Server 2022 Datacenter',
                'description' => 'Windows Server 2022 Datacenter - 16 Core + Installation Services',
                'category_id' => $categories['Servers']->id,
                'brand' => 'Microsoft',
                'model_number' => '2022-Datacenter-16Core',
                'specifications' => [
                    'type' => 'Software License',
                    'edition' => 'Datacenter',
                    'cores' => '16',
                    'includes' => 'Installation Services',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Colocation & Managed Services',
                'description' => 'Capex Payment For Colocation Services & Managed Services For AmanahRaya Trustees Berhad (ART)',
                'category_id' => $categories['Servers']->id,
                'brand' => 'Various',
                'model_number' => 'Colocation-Services',
                'specifications' => [
                    'type' => 'Managed Services',
                    'service_type' => 'Colocation & Managed Services',
                    'client' => 'AmanahRaya Trustees Berhad (ART)',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 36,
            ],
            // Audio Visual Models
            [
                'name' => 'HIKVISION INTERACTIVE DS-D5C7RB/B',
                'description' => 'HIKVISION INTERACTIVE MODEL : DS-D5C7RB/B (75 inch)',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'HIKVISION',
                'model_number' => 'DS-D5C7RB/B',
                'specifications' => [
                    'type' => 'Interactive Display',
                    'screen_size' => '75 inch',
                    'features' => ['Touch Screen', 'Interactive', '4K Display'],
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'HIKVISION MOBILE STAND DS-D5ABKY2-S',
                'description' => 'HIKVISION MOBILE STAND MODEL : DS-D5ABKY2-S',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'HIKVISION',
                'model_number' => 'DS-D5ABKY2-S',
                'specifications' => [
                    'type' => 'Mobile Stand',
                    'compatibility' => 'For Interactive Displays',
                    'mobility' => 'Mobile/Wheeled',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'HP POLY SYNC 40',
                'description' => 'HP POLY SYNC 40 USB-A USB-C SPEAKERPHONE',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'HP Poly',
                'model_number' => 'SYNC 40',
                'specifications' => [
                    'type' => 'Speakerphone',
                    'connectivity' => 'USB-A, USB-C',
                    'features' => ['Conference Speaker', 'Microphone', 'Noise Cancellation'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'Sony ZV-E10L Kit (1650) Camera',
                'description' => 'Sony ZV-E10L Kit (1650) Camera Back',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Sony',
                'model_number' => 'ZV-E10L',
                'specifications' => [
                    'type' => 'Camera',
                    'sensor' => 'APS-C',
                    'lens_kit' => '16-50mm',
                    'features' => ['Vlogging Camera', '4K Video', 'Interchangeable Lens'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 40,
            ],
            // Networking Models
            [
                'name' => 'D-Link Router Wireless N300M',
                'description' => 'D-Link Router Wireless N300M',
                'category_id' => $categories['Networking']->id,
                'brand' => 'D-Link',
                'model_number' => 'N300M',
                'specifications' => [
                    'type' => 'Wireless Router',
                    'wireless_standard' => 'N300',
                    'speed' => '300Mbps',
                    'frequency' => '2.4GHz',
                    'ports' => '4 x LAN, 1 x WAN',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 41,
            ],
            // Furniture Models
            [
                'name' => 'Manager Table Set',
                'description' => 'Manager Table Set',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Manager-Set',
                'specifications' => [
                    'type' => 'Office Table',
                    'category' => 'Manager Grade',
                    'material' => 'Wood/Metal',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 42,
            ],
            [
                'name' => 'Executive Mobile Rostrum',
                'description' => 'Executive Mobile Rostrum',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Mobile-Rostrum',
                'specifications' => [
                    'type' => 'Mobile Podium',
                    'features' => ['Mobile', 'Adjustable Height'],
                    'purpose' => 'Presentation',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 43,
            ],
            [
                'name' => 'Non Executive Workstation',
                'description' => 'Non Executive Workstation',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'NonExec-Workstation',
                'specifications' => [
                    'type' => 'Workstation Table',
                    'category' => 'Non-Executive Grade',
                    'configuration' => 'Standard Workstation',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'Executive Workstation',
                'description' => 'Executive Workstation',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Exec-Workstation',
                'specifications' => [
                    'type' => 'Workstation Table',
                    'category' => 'Executive Grade',
                    'configuration' => 'Premium Workstation',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 45,
            ],
            [
                'name' => 'Meeting Table',
                'description' => 'Meeting Table',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Meeting-Table',
                'specifications' => [
                    'type' => 'Conference Table',
                    'purpose' => 'Meeting Room',
                    'configuration' => 'Large Table',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 46,
            ],
            [
                'name' => 'Manager Workstation',
                'description' => 'Manager Workstation',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Manager-Workstation',
                'specifications' => [
                    'type' => 'Workstation Table',
                    'category' => 'Manager Grade',
                    'configuration' => 'Premium Manager Workstation',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 47,
            ],

            [
                'name' => 'Tessa Chair (Full Leather)',
                'description' => 'Tessa Chair Full Leather',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Tessa-Full-Leather',
                'specifications' => [
                    'type' => 'Meeting Chair',
                    'material' => 'Full Leather',
                    'features' => ['Executive Chair', 'High Back'],
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 48,
            ],
            [
                'name' => 'Highback Leather Chair (Black)',
                'description' => 'Highback Leather Chair Black',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Highback-Leather-Black',
                'specifications' => [
                    'type' => 'Executive Chair',
                    'material' => 'Leather',
                    'color' => 'Black',
                    'features' => ['High Back', 'Executive', 'Adjustable'],
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 49,
            ],
            [
                'name' => 'Single sided library shelf',
                'description' => 'Single sided library shelf',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Library-Shelf-Single',
                'specifications' => [
                    'type' => 'Library Shelf',
                    'configuration' => 'Single Sided',
                    'purpose' => 'Library Storage',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 50,
            ],
            [
                'name' => 'Full height cabinet',
                'description' => 'Full height cabinet',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Cabinet-Full-Height',
                'specifications' => [
                    'type' => 'Storage Cabinet',
                    'height' => 'Full Height',
                    'purpose' => 'General Storage',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 51,
            ],
            [
                'name' => 'Full height cabinet & Sliding cabinet',
                'description' => 'Full height cabinet with sliding doors',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Cabinet-Full-Sliding',
                'specifications' => [
                    'type' => 'Storage Cabinet',
                    'height' => 'Full Height',
                    'doors' => 'Sliding Doors',
                    'features' => ['Combination Unit'],
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 52,
            ],
            [
                'name' => 'Filing / Shelves',
                'description' => 'Filing cabinet and shelves',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Filing-Shelves',
                'specifications' => [
                    'type' => 'Filing Cabinet',
                    'purpose' => 'Document Storage',
                    'configuration' => 'Shelving System',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 53,
            ],
            [
                'name' => '15 Compartment Steel Locker',
                'description' => '15 Compartment Steel Locker',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Steel-Locker-15',
                'specifications' => [
                    'type' => 'Steel Locker',
                    'compartments' => '15',
                    'material' => 'Steel',
                    'purpose' => 'Personal Storage',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 54,
            ],
            [
                'name' => 'Classico Double Seater Sofa Full Leather',
                'description' => 'Classico Double Seater Sofa Full Leather',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Classico',
                'model_number' => 'Sofa-Double-Classico',
                'specifications' => [
                    'type' => 'Sofa',
                    'seating_capacity' => '2 Seater',
                    'material' => 'Full Leather',
                    'style' => 'Classico',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 55,
            ],
            [
                'name' => 'Double Seater Sofa Full Leather',
                'description' => 'Double Seater Sofa Full Leather',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Sofa-Double-Standard',
                'specifications' => [
                    'type' => 'Sofa',
                    'seating_capacity' => '2 Seater',
                    'material' => 'Full Leather',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 56,
            ],
            [
                'name' => 'Single Seater Sofa Full Leather',
                'description' => 'Single Seater Sofa Full Leather',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Sofa-Single-Standard',
                'specifications' => [
                    'type' => 'Sofa',
                    'seating_capacity' => '1 Seater',
                    'material' => 'Full Leather',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 57,
            ],
            [
                'name' => '4 Bays Mobile Compactor',
                'description' => '4 Bays Mobile Compactor for document storage',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Office Furniture',
                'model_number' => 'Mobile-Compactor-4Bay',
                'specifications' => [
                    'type' => 'Mobile Compactor',
                    'bays' => '4',
                    'mobility' => 'Mobile/Rolling',
                    'purpose' => 'Document Storage',
                    'features' => ['Space Saving', 'Mobile System', 'High Density Storage'],
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 58,
            ],
            [
                'name' => 'Lion FRC 4 Drawer Model PP4',
                'description' => 'Lion FRC 4 Drawer Safety Box Model PP4',
                'category_id' => $categories['Furniture & Fittings']->id,
                'brand' => 'Lion',
                'model_number' => 'FRC-PP4',
                'specifications' => [
                    'type' => 'Safety Box',
                    'drawers' => '4',
                    'model' => 'PP4',
                    'features' => ['Fire Resistant', 'Document Security', 'Locking System'],
                    'security_level' => 'FRC (Fire Resistant Cabinet)',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 59,
            ],
            // Office Equipment (Others) Models
            [
                'name' => 'Pop-Up System Set',
                'description' => '1 Set Pop-Up System for presentations and displays',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Various',
                'model_number' => 'Pop-Up-System-Set',
                'specifications' => [
                    'type' => 'Presentation Equipment',
                    'features' => ['Portable', 'Pop-Up Display', 'Presentation System'],
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 60,
            ],
            [
                'name' => 'Shredder Machine GBB86CD/GBB81S',
                'description' => 'Shredder machine model GBB86CD/GBB81S',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Generic',
                'model_number' => 'GBB86CD/GBB81S',
                'specifications' => [
                    'type' => 'Paper Shredder',
                    'shred_type' => 'Cross Cut',
                    'capacity' => 'Standard',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 61,
            ],
            [
                'name' => 'GBC Binder Model C340',
                'description' => 'GBC Binder Model C340 for document binding',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'GBC',
                'model_number' => 'C340',
                'specifications' => [
                    'type' => 'Document Binder',
                    'brand' => 'GBC',
                    'purpose' => 'Document Binding',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 62,
            ],
            [
                'name' => 'Banquet Chair Trolley',
                'description' => 'Banquet Chair Trolley Size: 610W X 625 L X 1135H',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Office Equipment',
                'model_number' => 'Chair-Trolley-Standard',
                'specifications' => [
                    'type' => 'Chair Trolley',
                    'dimensions' => '610W X 625L X 1135H',
                    'purpose' => 'Chair Transportation',
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 63,
            ],
            [
                'name' => 'Magnetic Pop Up Backdrop HP01',
                'description' => 'Magnetic Pop Up Backdrop - Code HP01',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Various',
                'model_number' => 'HP01',
                'specifications' => [
                    'type' => 'Display Backdrop',
                    'features' => ['Magnetic', 'Pop-Up', 'Portable'],
                    'purpose' => 'Events and Presentations',
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 64,
            ],
            [
                'name' => 'Table Mat (Full Leather) Black',
                'description' => 'Table Mat Full Leather Black',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Office Accessories',
                'model_number' => 'Table-Mat-Leather-Black',
                'specifications' => [
                    'type' => 'Table Mat',
                    'material' => 'Full Leather',
                    'color' => 'Black',
                ],
                'warranty_period' => 60,
                'status' => true,
                'sort_order' => 65,
            ],
            [
                'name' => 'Polycom Conference Call Equipment',
                'description' => 'Polycom Conference Call Equipment',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Polycom',
                'model_number' => 'Conference-Call-System',
                'specifications' => [
                    'type' => 'Conference System',
                    'brand' => 'Polycom',
                    'purpose' => 'Audio/Video Conferencing',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 66,
            ],
            [
                'name' => 'EBA Paper Shredder CrossCut',
                'description' => 'EBA Paper Shredder CrossCut Models',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'EBA',
                'model_number' => 'EBA-Shredder-Series',
                'specifications' => [
                    'type' => 'Paper Shredder',
                    'shred_type' => 'Cross Cut',
                    'brand' => 'EBA',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 67,
            ],
            [
                'name' => 'Water Dispenser Floor Standing',
                'description' => 'Water Dispenser Floor Standing Models',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Various',
                'model_number' => 'Water-Dispenser-Floor',
                'specifications' => [
                    'type' => 'Water Dispenser',
                    'style' => 'Floor Standing',
                    'features' => ['Hot/Cold Water'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 68,
            ],
            [
                'name' => 'ELID Terminal',
                'description' => 'ELID Terminal for access control',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'ELID',
                'model_number' => 'ELID-Terminal',
                'specifications' => [
                    'type' => 'Access Control Terminal',
                    'purpose' => 'Security Access',
                    'features' => ['Electronic Lock'],
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 69,
            ],
            [
                'name' => 'Cuckoo Water Purifier CP-DN1201S',
                'description' => 'Cuckoo Water Purifier Model CP-DN1201S',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Cuckoo',
                'model_number' => 'CP-DN1201S',
                'specifications' => [
                    'type' => 'Water Purifier',
                    'brand' => 'Cuckoo',
                    'model' => 'CP-DN1201S',
                    'features' => ['Water Purification', 'Filter System'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 70,
            ],
            [
                'name' => 'Heavy Duty Paper Punch PU-3000',
                'description' => '2-Hole Heavy Duty Paper Punch (PU-3000)',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Various',
                'model_number' => 'PU-3000',
                'specifications' => [
                    'type' => 'Paper Punch',
                    'holes' => '2-Hole',
                    'capacity' => 'Heavy Duty',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 71,
            ],
            [
                'name' => 'Double Sided Mobile Magnetic Whiteboard',
                'description' => 'Double sided mobile magnetic whiteboard (4\'x3\')',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Office Equipment',
                'model_number' => 'Whiteboard-Double-Mobile',
                'specifications' => [
                    'type' => 'Whiteboard',
                    'size' => '4\'x3\'',
                    'features' => ['Double Sided', 'Mobile', 'Magnetic'],
                    'mobility' => 'Mobile with wheels',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 72,
            ],
            [
                'name' => 'Magnetic Whiteboard Custom 16\'x4\'',
                'description' => 'Magnetic Whiteboard (custom made) 16\'x4\'',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Office Equipment',
                'model_number' => 'Whiteboard-Custom-16x4',
                'specifications' => [
                    'type' => 'Whiteboard',
                    'size' => '16\'x4\'',
                    'features' => ['Custom Size', 'Magnetic'],
                    'custom' => 'Yes',
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 73,
            ],
            // Office Equipment (Refrigerator) Models
            [
                'name' => 'Panasonic Fridge',
                'description' => 'Panasonic Refrigerator for office pantry use',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Panasonic',
                'model_number' => 'Office-Fridge-Panasonic',
                'specifications' => [
                    'type' => 'Refrigerator',
                    'brand' => 'Panasonic',
                    'purpose' => 'Pantry/Office Use',
                    'features' => ['Single Door', 'Freezer Compartment'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 74,
            ],
            [
                'name' => 'Sharp Fridge',
                'description' => 'Sharp Refrigerator for office pantry use',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Sharp',
                'model_number' => 'Office-Fridge-Sharp',
                'specifications' => [
                    'type' => 'Refrigerator',
                    'brand' => 'Sharp',
                    'purpose' => 'Pantry/Office Use',
                    'features' => ['Single Door', 'Freezer Compartment'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 75,
            ],
            // Office Equipment (Audio Visuals) Models
            [
                'name' => 'PA System - ARTB',
                'description' => 'PA System for AmanahRaya Trustees Berhad',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Various',
                'model_number' => 'PA-System-ARTB',
                'specifications' => [
                    'type' => 'Public Address System',
                    'purpose' => 'Audio Amplification',
                    'features' => ['Amplifier', 'Mixer', 'Speakers'],
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 76,
            ],
            [
                'name' => '2 Way Speaker',
                'description' => '2 Way Speaker for audio systems',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Various',
                'model_number' => 'Speaker-2Way',
                'specifications' => [
                    'type' => 'Speaker',
                    'configuration' => '2-Way',
                    'purpose' => 'Audio Output',
                ],
                'warranty_period' => 24,
                'status' => true,
                'sort_order' => 77,
            ],
            [
                'name' => 'Canon IXUS 8015 Digital Camera',
                'description' => 'Canon IXUS 8015 Digital Camera',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Canon',
                'model_number' => 'IXUS 8015',
                'specifications' => [
                    'type' => 'Digital Camera',
                    'series' => 'IXUS',
                    'model' => '8015',
                    'features' => ['Compact', 'Digital'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 78,
            ],
            [
                'name' => 'Samsung Full HD LCD TV',
                'description' => 'Samsung Full HD LCD TV Model LA46C550',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Samsung',
                'model_number' => 'LA46C550',
                'specifications' => [
                    'type' => 'LCD Television',
                    'size' => '46 inch',
                    'resolution' => 'Full HD',
                    'features' => ['LCD Display', 'Full HD'],
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 79,
            ],
            [
                'name' => 'Sony Digital Voice Recorder',
                'description' => 'Sony Digital Voice Recorder ICD SX713',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Sony',
                'model_number' => 'ICD SX713',
                'specifications' => [
                    'type' => 'Voice Recorder',
                    'model' => 'ICD SX713',
                    'features' => ['Digital Recording', 'Portable'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 80,
            ],
            [
                'name' => 'Canon EOS M-Kit (EF M22)',
                'description' => 'Canon EOS M-Kit with EF M22 lens',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Canon',
                'model_number' => 'EOS M-Kit',
                'specifications' => [
                    'type' => 'Mirrorless Camera',
                    'series' => 'EOS M',
                    'lens' => 'EF M22',
                    'features' => ['Interchangeable Lens', 'Kit Set'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 81,
            ],
            [
                'name' => 'Panasonic LCD Projector',
                'description' => 'Panasonic LCD Projector Model PT-LB3EA',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Panasonic',
                'model_number' => 'PT-LB3EA',
                'specifications' => [
                    'type' => 'LCD Projector',
                    'resolution' => 'XGA',
                    'brightness' => '3200 ANSI Lumens',
                    'features' => ['LCD Technology', 'XGA Resolution'],
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 82,
            ],
            [
                'name' => 'IVA Wireless Microphone System',
                'description' => 'IVA Wireless Microphone System',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'IVA',
                'model_number' => 'Wireless-Mic-System',
                'specifications' => [
                    'type' => 'Wireless Microphone System',
                    'features' => ['Wireless', 'UHF/VHF', 'Receiver'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 83,
            ],
            [
                'name' => 'Canon EOS M50 Camera',
                'description' => 'Canon EOS M50 Mirrorless Camera',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'Canon',
                'model_number' => 'EOS M50',
                'specifications' => [
                    'type' => 'Mirrorless Camera',
                    'series' => 'EOS M50',
                    'features' => ['4K Video', 'Interchangeable Lens', 'Digital'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 84,
            ],
            [
                'name' => 'BenQ Projector',
                'description' => 'BenQ Projector',
                'category_id' => $categories['Audio Visual']->id,
                'brand' => 'BenQ',
                'model_number' => 'Projector-BenQ',
                'specifications' => [
                    'type' => 'Projector',
                    'brand' => 'BenQ',
                    'features' => ['HD/4K Capable', 'Presentation'],
                ],
                'warranty_period' => 36,
                'status' => true,
                'sort_order' => 85,
            ],
            // Office Equipment (Keyphone) Models
            [
                'name' => 'Toshiba Digital LCD Keyphone Model DP512',
                'description' => 'Toshiba Digital LCD Keyphone Model DP512',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Toshiba',
                'model_number' => 'DP512',
                'specifications' => [
                    'type' => 'Digital Keyphone',
                    'brand' => 'Toshiba',
                    'model' => 'DP512',
                    'features' => ['LCD Display', 'Digital', 'Multi-line'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 86,
            ],
            [
                'name' => 'Toshiba 10 key LCD Display Phone Model DP5122DSD',
                'description' => 'Toshiba 10 key LCD Display Phone Model DP5122DSD',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Toshiba',
                'model_number' => 'DP5122DSD',
                'specifications' => [
                    'type' => 'Digital Keyphone',
                    'brand' => 'Toshiba',
                    'model' => 'DP5122DSD',
                    'keys' => '10-key',
                    'features' => ['LCD Display', 'Digital', '10-key Pad'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 87,
            ],
            [
                'name' => 'Toshiba Digital LCD Display Telephone Model DP5130D-SDL',
                'description' => 'Toshiba Digital LCD Display Telephone Model DP5130D-SDL',
                'category_id' => $categories['Office Equipment']->id,
                'brand' => 'Toshiba',
                'model_number' => 'DP5130D-SDL',
                'specifications' => [
                    'type' => 'Digital Telephone',
                    'brand' => 'Toshiba',
                    'model' => 'DP5130D-SDL',
                    'features' => ['LCD Display', 'Digital', 'Enhanced Features'],
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 88,
            ],
            // Renovation Models
            [
                'name' => 'Office Renovation',
                'description' => 'Office renovation and improvement works',
                'category_id' => $categories['Renovation']->id,
                'brand' => 'Various Contractors',
                'model_number' => 'Office-Renovation',
                'specifications' => [
                    'type' => 'Capital Improvement',
                    'category' => 'Renovation Works',
                    'purpose' => 'Office Space Improvement',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 89,
            ],
            [
                'name' => 'Filing / Shelves Renovation',
                'description' => 'Filing and shelves installation as part of renovation',
                'category_id' => $categories['Renovation']->id,
                'brand' => 'Various Contractors',
                'model_number' => 'Filing-Shelves-Renovation',
                'specifications' => [
                    'type' => 'Built-in Furniture',
                    'category' => 'Renovation Works',
                    'purpose' => 'Storage Installation',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 90,
            ],
            [
                'name' => 'Smart TV Installation',
                'description' => 'Smart TV installation as part of renovation works',
                'category_id' => $categories['Renovation']->id,
                'brand' => 'Various',
                'model_number' => 'Smart-TV-Installation',
                'specifications' => [
                    'type' => 'AV Installation',
                    'category' => 'Renovation Works',
                    'purpose' => 'Audio Visual Setup',
                ],
                'warranty_period' => 12,
                'status' => true,
                'sort_order' => 91,
            ],
        ];

        foreach ($models as $model) {
            ModelType::create($model);
        }

        $this->command->info('Successfully seeded '.count($models).' model types.');
    }
}
