<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StationaryItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'name' => 'A3 PAPER',
                'description' => 'A3 PAPER',
                'category' => 'paper',
                'unit' => 'pcs',
                'sku' => 'A3-PAPER-001',
                'min_stock' => 50,
                'current_stock' => 202,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Paper Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'A4 HARD COVER',
                'description' => 'A4 HARD COVER TRANSPARENT',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'A4-HC-TP-001',
                'min_stock' => 20,
                'current_stock' => 70,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'A4 PAPER',
                'description' => 'A4 PAPER',
                'category' => 'paper',
                'unit' => 'reams',
                'sku' => 'A4-PAPER-001',
                'min_stock' => 30,
                'current_stock' => 184,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Paper Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'A4 PAPER (BLUE)',
                'description' => 'A4 PAPER (BLUE)',
                'category' => 'paper',
                'unit' => 'pcs',
                'sku' => 'A4-PAPER-BLUE-001',
                'min_stock' => 10,
                'current_stock' => 8,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Paper Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'A4 PAPER (ORANGE)',
                'description' => 'A4 PAPER (ORANGE)',
                'category' => 'paper',
                'unit' => 'pcs',
                'sku' => 'A4-PAPER-ORG-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Paper Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'A4 PAPER (YELLOW)',
                'description' => 'A4 PAPER (YELLOW)',
                'category' => 'paper',
                'unit' => 'pcs',
                'sku' => 'A4-PAPER-YELLOW-001',
                'min_stock' => 10,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Paper Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ABBA ARCH 3 FILE',
                'description' => 'ABBA ARCH 3 FILE',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'ABBA-ARCH-3-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ARTLINE 500',
                'description' => 'WHITEBOARD (BLUE)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'ARTLINE-500-BLUE-001',
                'min_stock' => 10,
                'current_stock' => 11,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ARTLINE 500 WHITEBOARD',
                'description' => 'WHITEBOARD (BLACK)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'ARTLINE-500-BLACK-001',
                'min_stock' => 10,
                'current_stock' => 10,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ARTLINE 70 PERMANENT BLK',
                'description' => 'PERMANENT(BLACK)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'ARTLINE-70-BLACK-001',
                'min_stock' => 10,
                'current_stock' => 6,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ARTLINE500 WHITEBOARD',
                'description' => 'WHITEBOARD (RED)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'ARTLINE-500-RED-001',
                'min_stock' => 10,
                'current_stock' => 12,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BINDER CLIPS 32MM',
                'description' => 'BINDER CLIPS 32MM',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'BINDER-CLIP-32MM-001',
                'min_stock' => 20,
                'current_stock' => 11,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Clip Container',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BINDING COMB 10MM',
                'description' => 'UNIQUE LOCK BINDER 10MM',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'BINDING-COMB-10MM-001',
                'min_stock' => 20,
                'current_stock' => 45,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Binding Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BINDING COMB 5MM',
                'description' => 'UNIQUE LOCK BINDER 5MM',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'BINDING-COMB-5MM-001',
                'min_stock' => 15,
                'current_stock' => 17,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Binding Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BROWN TAPE (BIG)',
                'description' => 'BROWN TAPE (BIG)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'BROWN-TAPE-BIG-001',
                'min_stock' => 10,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tape Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BULLET MAX 1210FA-H23/10',
                'description' => 'BULLET MAX 1210FA-H23/10',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'BULLET-MAX-1210FA-001',
                'min_stock' => 5,
                'current_stock' => 3,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stapler Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BULLET MAX 121FA-H23/17',
                'description' => 'BULLET MAX 121FA-H23/17',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'BULLET-MAX-121FA-001',
                'min_stock' => 5,
                'current_stock' => 8,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stapler Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BULLET STAPLES MAX NO-10',
                'description' => 'BULLET STAPLES',
                'category' => 'desk',
                'unit' => 'boxes',
                'sku' => 'BULLET-STAPLES-10-001',
                'min_stock' => 10,
                'current_stock' => 45,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stapler Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BUTTERFLY CLIP',
                'description' => 'BINDER CLIPS 25MM',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'BUTTERFLY-CLIP-25MM-001',
                'min_stock' => 15,
                'current_stock' => 9,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Clip Container',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'BUTTERFLY CLIPS',
                'description' => 'BINDER CLIPS 41MM',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'BUTTERFLY-CLIP-41MM-001',
                'min_stock' => 10,
                'current_stock' => 12,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Clip Container',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'CALCULATOR',
                'description' => 'CALCULATOR CANON 12 DIGITS',
                'category' => 'computer',
                'unit' => 'pcs',
                'sku' => 'CALC-CANON-12D-001',
                'min_stock' => 2,
                'current_stock' => 3,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Equipment Shelf',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'COMB BINDING 6MM BLACK',
                'description' => 'BINDER 6MM',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'COMB-BINDING-6MM-001',
                'min_stock' => 10,
                'current_stock' => 9,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Binding Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'COP',
                'description' => 'COP DATE',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'COP-DATE-001',
                'min_stock' => 5,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'CORRECTING TAPE',
                'description' => 'CORRECTING TAPE PELIKAN',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'CORRECTING-TAPE-001',
                'min_stock' => 5,
                'current_stock' => 6,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Writing Tools',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'CREAMER 50STICK/PER PKT',
                'description' => 'CREAMER 50STICK/PER PKT',
                'category' => 'other',
                'unit' => 'packs',
                'sku' => 'CREAMER-50STICK-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pantry',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'DAF P GUNA METERAI SYKT',
                'description' => 'DAF P GUNA METERAI SYKT',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'DAF-METERAI-001',
                'min_stock' => 5,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Admin Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'DISHWASHER',
                'description' => 'DISHWASHER',
                'category' => 'cleaning',
                'unit' => 'pcs',
                'sku' => 'DISHWASHER-001',
                'min_stock' => 3,
                'current_stock' => 5,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Cleaning Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'DOUBLE PUNCH',
                'description' => 'DOUBLE PUNCH MAX DP -2 HOLE',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'DOUBLE-PUNCH-001',
                'min_stock' => 5,
                'current_stock' => 12,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tools Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ENVELOPE A3',
                'description' => 'ENVELOPE A3',
                'category' => 'mailing',
                'unit' => 'pcs',
                'sku' => 'ENVELOPE-A3-001',
                'min_stock' => 50,
                'current_stock' => 115,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Envelope Box',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ENVELOPE NON WINDOW A4',
                'description' => 'ENVELOPE NON WINDOW A4 9 X 12.75',
                'category' => 'mailing',
                'unit' => 'pcs',
                'sku' => 'ENVELOPE-A4-NW-001',
                'min_stock' => 10,
                'current_stock' => 5,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Envelope Box',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ENVELOPE WINDOW',
                'description' => 'ENVELOPE WINDOW 4.38 X 8.75',
                'category' => 'mailing',
                'unit' => 'pcs',
                'sku' => 'ENVELOPE-WINDOW-001',
                'min_stock' => 10,
                'current_stock' => 7,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Envelope Box',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'ERASER',
                'description' => 'ERASER',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'ERASER-001',
                'min_stock' => 20,
                'current_stock' => 28,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Writing Tools',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'EXTENSION CORD',
                'description' => 'EXTENSION CORD',
                'category' => 'computer',
                'unit' => 'pcs',
                'sku' => 'EXTENSION-CORD-001',
                'min_stock' => 2,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Electrical Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FABER CASTLE CLICK PEN',
                'description' => 'PEN 0.7 (BLACK)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PEN-FC-BLACK-001',
                'min_stock' => 30,
                'current_stock' => 32,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pen Stand',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FABERCASTLE CLICK PEN',
                'description' => 'PEN 0.7 (BLUE)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PEN-FC-BLUE-001',
                'min_stock' => 30,
                'current_stock' => 36,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pen Stand',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FABERCASTLE CLICK PEN0.7',
                'description' => 'PEN 0.7 (RED)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PEN-FC-RED-001',
                'min_stock' => 30,
                'current_stock' => 91,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pen Stand',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FAIL CBF PVC',
                'description' => 'FAIL CBF PVC 2D RING (25MM)',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'FAIL-CBF-25MM-001',
                'min_stock' => 5,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FAIL CBF PVC 2D RING',
                'description' => 'FAIL CBF PVC 2D RING (50MM)',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'FAIL-CBF-50MM-001',
                'min_stock' => 5,
                'current_stock' => 3,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FAIL PUTIH',
                'description' => 'L SHAPE A4 DOC FOLDER',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'FAIL-PUTIH-001',
                'min_stock' => 20,
                'current_stock' => 6,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'FARM FRESH',
                'description' => 'CHOCOMALT',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'FARM-FRESH-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pantry',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GLUE STICK',
                'description' => 'GLUE STICK',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'GLUE-STICK-001',
                'min_stock' => 10,
                'current_stock' => 5,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Adhesive Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'GREEN TAG',
                'description' => 'GREEN TAG - T8',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'GREEN-TAG-001',
                'min_stock' => 20,
                'current_stock' => -5,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Labeling Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'HARD COVER BOOK',
                'description' => 'HARD COVER BOOK LONG 400PG',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'HARD-COVER-400-001',
                'min_stock' => 3,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Book Shelf',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'HARD COVER BOOK (LONG)',
                'description' => 'HARD COVER BOOK (LONG) 200 PGS',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'HARD-COVER-200-001',
                'min_stock' => 3,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Book Shelf',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'HARD COVER BOOK LONG',
                'description' => 'HARD COVER BOOK LONG (LEDGER)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'HARD-COVER-LEDGER-001',
                'min_stock' => 3,
                'current_stock' => 3,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Book Shelf',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'HARDCOVER SQUARE BOOK',
                'description' => 'HARDCOVER SQUARE BOOK',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'HARD-COVER-SQUARE-001',
                'min_stock' => 2,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Book Shelf',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'HILIGHTER (RED)',
                'description' => 'HILIGHTER (PINK)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'HIGHLIGHTER-PINK-001',
                'min_stock' => 15,
                'current_stock' => 10,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'HILIGHTER (YELLOW)',
                'description' => 'HILIGHTER (YELLOW)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'HIGHLIGHTER-YELLOW-001',
                'min_stock' => 15,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hanging Tissue',
                'description' => 'Tisu Pantry',
                'category' => 'cleaning',
                'unit' => 'pcs',
                'sku' => 'HANGING-TISSUE-001',
                'min_stock' => 5,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Cleaning Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'KERTAS MINIT',
                'description' => 'KERTAS MINIT MESYUARAT',
                'category' => 'paper',
                'unit' => 'pcs',
                'sku' => 'KERTAS-MINIT-001',
                'min_stock' => 5,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Paper Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'KNIFE',
                'description' => 'KNIFE',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'KNIFE-001',
                'min_stock' => 5,
                'current_stock' => 12,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tools Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'LETTER HEAD ARTB',
                'description' => 'LETTER HEAD ARTB',
                'category' => 'paper',
                'unit' => 'pcs',
                'sku' => 'LETTER-HEAD-ARTB-001',
                'min_stock' => 50,
                'current_stock' => 123,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Paper Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'LIQUID PAPER',
                'description' => 'LIQUID PAPER',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'LIQUID-PAPER-001',
                'min_stock' => 10,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Writing Tools',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'MAGAZINE BOX',
                'description' => 'MAGAZINE BOX',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'MAGAZINE-BOX-001',
                'min_stock' => 10,
                'current_stock' => 20,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'MANAGEMENT FILE',
                'description' => 'MANAGEMENT FILE',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'MANAGEMENT-FILE-001',
                'min_stock' => 15,
                'current_stock' => 28,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'MILO 2KG',
                'description' => 'MILO 2KG',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'MILO-2KG-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pantry',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'NESCAFE',
                'description' => 'NESCAFE',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'NESCAFE-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pantry',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'PAPER CLIP SMALL',
                'description' => 'PAPER CLIP SMALL',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'PAPER-CLIP-SMALL-001',
                'min_stock' => 20,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Clip Container',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'PAPER CLIPS GIANT',
                'description' => 'PAPER CLIPS JUMBO',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'PAPER-CLIP-JUMBO-001',
                'min_stock' => 10,
                'current_stock' => 7,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Clip Container',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'PEA FORM',
                'description' => 'PEA FORM',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'PEA-FORM-001',
                'min_stock' => 5,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Admin Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'PEN PILOT G-2 0.7',
                'description' => 'PEN PILOT G-2 0.7',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PEN-PILOT-G2-001',
                'min_stock' => 20,
                'current_stock' => 30,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pen Stand',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'PENCIL 2B',
                'description' => 'PENCIL 2B',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PENCIL-2B-001',
                'min_stock' => 20,
                'current_stock' => 16,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Writing Tools',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'PETTY CASH VOUCHER',
                'description' => 'PETTY CASH VOUCHER',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'PETTY-CASH-VOUCHER-001',
                'min_stock' => 10,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Admin Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'POST IT',
                'description' => 'POST IT 3"X5"',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'POST-IT-3X5-001',
                'min_stock' => 10,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Note Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'POST-IT',
                'description' => 'POST-IT 3"X3"',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'POST-IT-3X3-001',
                'min_stock' => 10,
                'current_stock' => 9,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Note Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'POST-IT (SIGN HERE)',
                'description' => 'POST-IT (SIGN HERE)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'POST-IT-SIGN-001',
                'min_stock' => 10,
                'current_stock' => 11,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Note Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'REFILL PEN PILOT G2 0.7',
                'description' => 'REFILL PEN PILOT G2 0.7',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'REFILL-PILOT-G2-001',
                'min_stock' => 20,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pen Stand',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'RIBBON TYPEWRITTER',
                'description' => 'RIBBON NAKAJIMA AE800',
                'category' => 'computer',
                'unit' => 'pcs',
                'sku' => 'RIBBON-TYPEWRITER-001',
                'min_stock' => 2,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Equipment Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'RUBBER BAND SMALL',
                'description' => 'RUBBER BAND SMALL',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'RUBBER-BAND-SMALL-001',
                'min_stock' => 10,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Clip Container',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'RULLER PLASTIC',
                'description' => 'RULLER PLASTIC',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'RULER-PLASTIC-001',
                'min_stock' => 10,
                'current_stock' => 6,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Writing Tools',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'SCISSORS',
                'description' => 'SCISSORS',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'SCISSORS-002',
                'min_stock' => 5,
                'current_stock' => 11,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tools Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'SHARPENER',
                'description' => 'SHARPENER',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'SHARPENER-001',
                'min_stock' => 5,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Writing Tools',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'SHEETS PROTECTOR',
                'description' => 'SHEETS PROTECTOR',
                'category' => 'filing',
                'unit' => 'pcs',
                'sku' => 'SHEETS-PROTECTOR-001',
                'min_stock' => 20,
                'current_stock' => 80,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Filing Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'SHINY INK PAD R542D',
                'description' => 'SHINY INK PAD R542D BLACK/RED',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'INK-PAD-R542D-001',
                'min_stock' => 5,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'SINGLE HOLE PUNCH',
                'description' => 'SINGLE HOLE PUNCH',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'SINGLE-PUNCH-001',
                'min_stock' => 3,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tools Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD (BLACK)',
                'description' => 'STAMP PAD (BLACK)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-PAD-BLACK-001',
                'min_stock' => 5,
                'current_stock' => 7,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD (BLUE)',
                'description' => 'STAMP PAD (BLUE)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-PAD-BLUE-001',
                'min_stock' => 5,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD (RED)',
                'description' => 'STAMP PAD (RED)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-PAD-RED-001',
                'min_stock' => 5,
                'current_stock' => 8,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD INK',
                'description' => 'S-853-7',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-S853-001',
                'min_stock' => 5,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD INK (BLACK)',
                'description' => 'STAMP PAD INK (BLACK)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-BLACK-001',
                'min_stock' => 10,
                'current_stock' => 7,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD INK (BLUE)',
                'description' => 'STAMP PAD INK (BLUE)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-BLUE-001',
                'min_stock' => 10,
                'current_stock' => 8,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD INK (RED)',
                'description' => 'STAMP PAD INK (RED)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-RED-001',
                'min_stock' => 10,
                'current_stock' => 8,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMP PAD INK SHINNY',
                'description' => 'S-852-7',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-S852-001',
                'min_stock' => 5,
                'current_stock' => 10,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMPAD INK SHINNY',
                'description' => 'S-829-7',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-S829-001',
                'min_stock' => 5,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMPAD INK SHINY',
                'description' => 'S-828D-7 (BLACK/RED)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-S828D-001',
                'min_stock' => 5,
                'current_stock' => 10,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAMPPAD INK SHINNY B',
                'description' => 'S-828-7 (BLACK)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'STAMP-INK-S828-001',
                'min_stock' => 5,
                'current_stock' => 10,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stamping Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'STAPLER-MAX HD 10',
                'description' => 'STAPLER-MAX HD 10',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'STAPLER-MAX-10-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Stapler Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'SUGAR',
                'description' => 'SUGAR',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'SUGAR-001',
                'min_stock' => 10,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pantry',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'TAPE-LOYTAPE 25MM X 15MM',
                'description' => 'TAPE-LOYTAPE 25MM X 15MM',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'TAPE-LOYTAPE-001',
                'min_stock' => 5,
                'current_stock' => 5,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tape Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'TELEFON SINGLE LINE',
                'description' => 'TELEFON SINGLE LINE',
                'category' => 'computer',
                'unit' => 'pcs',
                'sku' => 'TELEPHONE-SINGLE-001',
                'min_stock' => 2,
                'current_stock' => 2,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Equipment Shelf',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'TISU',
                'description' => 'TISU',
                'category' => 'cleaning',
                'unit' => 'pcs',
                'sku' => 'TISSUE-001',
                'min_stock' => 10,
                'current_stock' => 3,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Cleaning Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'TRANSPARENT TAPE',
                'description' => 'TRANSPARENT TAPE (BIG)',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'TAPE-TRANSPARENT-001',
                'min_stock' => 5,
                'current_stock' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tape Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'TRAY IN OUT',
                'description' => 'TRAY IN OUT',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'TRAY-IN-OUT-001',
                'min_stock' => 3,
                'current_stock' => 1,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Organization Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'UHU GLUE LIQUID',
                'description' => 'UHU GLUE LIQUID 50ML',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'UHU-GLUE-001',
                'min_stock' => 10,
                'current_stock' => 4,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Adhesive Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'UNI-BALL SIGNO',
                'description' => 'UNI-BALL SIGNO (UM-153 INK BLACK)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'UNIBALL-SIGNO-001',
                'min_stock' => 20,
                'current_stock' => 24,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pen Stand',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'UNISIGNO PEN BLACK',
                'description' => 'UNISIGNO PEN UMN-153 BLACK',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'UNISIGNO-BLACK-001',
                'min_stock' => 20,
                'current_stock' => 38,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Pen Stand',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'WASHING SPONGE',
                'description' => 'WASHING SPONGE',
                'category' => 'cleaning',
                'unit' => 'pcs',
                'sku' => 'WASHING-SPONGE-001',
                'min_stock' => 20,
                'current_stock' => 47,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Cleaning Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'WHITEBOARD MAKER (BLUE)',
                'description' => 'ARTLINE 70 PERMANENT(BLUE)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'WHITEBOARD-BLUE-001',
                'min_stock' => 10,
                'current_stock' => 8,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'WHITEBOARD MAKER (RED)',
                'description' => 'ARTLINE 70 PERMANENT RED)',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'WHITEBOARD-RED-001',
                'min_stock' => 10,
                'current_stock' => 10,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Marker Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'White Cotton Tape',
                'description' => 'Cotton Tape',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'COTTON-TAPE-001',
                'min_stock' => 5,
                'current_stock' => 7,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'supplier' => 'General Supplier',
                'location' => 'Tape Drawer',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert all items
        DB::table('stationary_items')->insert($items);

        $this->command->info('Successfully seeded all stationary items from Excel data with zero cost and selling prices.');
    }
}
