<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StationaryItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // Writing Instruments
            [
                'name' => 'Ballpoint Pens (Blue)',
                'description' => 'Standard blue ballpoint pens for everyday office use',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PEN-BLUE-001',
                'min_stock' => 50,
                'current_stock' => 120,
                'cost_price' => 0.50,
                'selling_price' => 1.20,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet A',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ballpoint Pens (Black)',
                'description' => 'Standard black ballpoint pens',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PEN-BLACK-001',
                'min_stock' => 50,
                'current_stock' => 85,
                'cost_price' => 0.50,
                'selling_price' => 1.20,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet A',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mechanical Pencils 0.7mm',
                'description' => 'Professional mechanical pencils with 0.7mm lead',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'PENCIL-MECH-07',
                'min_stock' => 20,
                'current_stock' => 35,
                'cost_price' => 1.20,
                'selling_price' => 2.50,
                'supplier' => 'Writing Instruments Ltd.',
                'location' => 'Stationary Cabinet A',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Permanent Markers',
                'description' => 'Black permanent markers for labeling',
                'category' => 'writing',
                'unit' => 'pcs',
                'sku' => 'MARKER-PERM-BLK',
                'min_stock' => 15,
                'current_stock' => 25,
                'cost_price' => 1.00,
                'selling_price' => 2.00,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet A',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Whiteboard Markers Set',
                'description' => 'Set of 4 colored whiteboard markers',
                'category' => 'writing',
                'unit' => 'sets',
                'sku' => 'MARKER-WB-SET4',
                'min_stock' => 10,
                'current_stock' => 18,
                'cost_price' => 3.50,
                'selling_price' => 6.00,
                'supplier' => 'Presentation Supplies Inc.',
                'location' => 'Meeting Room Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Paper Products
            [
                'name' => 'A4 Copy Paper',
                'description' => 'Standard A4 80gsm copy paper',
                'category' => 'paper',
                'unit' => 'reams',
                'sku' => 'PAPER-A4-80GSM',
                'min_stock' => 5,
                'current_stock' => 12,
                'cost_price' => 4.00,
                'selling_price' => 6.50,
                'supplier' => 'Paper Products Ltd.',
                'location' => 'Paper Storage Room',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sticky Notes 3x3',
                'description' => 'Yellow sticky notes 3x3 inches',
                'category' => 'paper',
                'unit' => 'packs',
                'sku' => 'STICKY-3X3-YLW',
                'min_stock' => 10,
                'current_stock' => 22,
                'cost_price' => 1.50,
                'selling_price' => 3.00,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet B',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Printing Paper A4 Premium',
                'description' => 'Premium A4 100gsm paper for important documents',
                'category' => 'paper',
                'unit' => 'reams',
                'sku' => 'PAPER-A4-100GSM',
                'min_stock' => 3,
                'current_stock' => 8,
                'cost_price' => 6.50,
                'selling_price' => 9.00,
                'supplier' => 'Paper Products Ltd.',
                'location' => 'Paper Storage Room',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Notebooks A5',
                'description' => 'A5 sized notebooks with 80 pages',
                'category' => 'paper',
                'unit' => 'pcs',
                'sku' => 'NOTEBOOK-A5-80P',
                'min_stock' => 15,
                'current_stock' => 30,
                'cost_price' => 1.80,
                'selling_price' => 3.50,
                'supplier' => 'Writing Instruments Ltd.',
                'location' => 'Stationary Cabinet B',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Desk Accessories
            [
                'name' => 'Desk Organizer Set',
                'description' => 'Set of desk organizers for pens and supplies',
                'category' => 'desk',
                'unit' => 'sets',
                'sku' => 'DESK-ORG-SET',
                'min_stock' => 5,
                'current_stock' => 8,
                'cost_price' => 8.00,
                'selling_price' => 15.00,
                'supplier' => 'Office Furniture Co.',
                'location' => 'Storage Room',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Stapler Standard',
                'description' => 'Standard office stapler',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'STAPLER-STD',
                'min_stock' => 8,
                'current_stock' => 15,
                'cost_price' => 3.50,
                'selling_price' => 7.00,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet C',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Staples Box',
                'description' => 'Box of 5000 standard staples',
                'category' => 'desk',
                'unit' => 'boxes',
                'sku' => 'STAPLES-5000',
                'min_stock' => 5,
                'current_stock' => 12,
                'cost_price' => 1.20,
                'selling_price' => 2.50,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet C',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Scissors 8-inch',
                'description' => '8-inch office scissors',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'SCISSORS-8IN',
                'min_stock' => 6,
                'current_stock' => 10,
                'cost_price' => 2.50,
                'selling_price' => 5.00,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet C',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Calculator Basic',
                'description' => 'Basic desktop calculator',
                'category' => 'desk',
                'unit' => 'pcs',
                'sku' => 'CALC-BASIC',
                'min_stock' => 4,
                'current_stock' => 7,
                'cost_price' => 5.00,
                'selling_price' => 12.00,
                'supplier' => 'Electronics Supplies',
                'location' => 'Electronics Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Filing Supplies
            [
                'name' => 'File Folders Letter Size',
                'description' => 'Letter size manila file folders',
                'category' => 'filing',
                'unit' => 'packs',
                'sku' => 'FOLDER-LTR-100',
                'min_stock' => 8,
                'current_stock' => 20,
                'cost_price' => 8.00,
                'selling_price' => 15.00,
                'supplier' => 'Filing Solutions Inc.',
                'location' => 'Filing Supplies Area',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Binder Clips Medium',
                'description' => 'Medium sized binder clips 32mm',
                'category' => 'filing',
                'unit' => 'boxes',
                'sku' => 'BINDER-CLIP-MED',
                'min_stock' => 10,
                'current_stock' => 25,
                'cost_price' => 3.00,
                'selling_price' => 6.00,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet C',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Paper Clips Box',
                'description' => 'Box of 1000 standard paper clips',
                'category' => 'filing',
                'unit' => 'boxes',
                'sku' => 'PAPERCLIPS-1000',
                'min_stock' => 8,
                'current_stock' => 18,
                'cost_price' => 1.50,
                'selling_price' => 3.00,
                'supplier' => 'Office Supplies Co.',
                'location' => 'Stationary Cabinet C',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Computer Supplies
            [
                'name' => 'USB Flash Drive 32GB',
                'description' => '32GB USB 3.0 flash drive',
                'category' => 'computer',
                'unit' => 'pcs',
                'sku' => 'USB-32GB-3.0',
                'min_stock' => 5,
                'current_stock' => 12,
                'cost_price' => 8.00,
                'selling_price' => 18.00,
                'supplier' => 'Electronics Supplies',
                'location' => 'Electronics Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mouse Pad',
                'description' => 'Standard office mouse pad',
                'category' => 'computer',
                'unit' => 'pcs',
                'sku' => 'MOUSE-PAD-STD',
                'min_stock' => 10,
                'current_stock' => 22,
                'cost_price' => 1.50,
                'selling_price' => 3.50,
                'supplier' => 'Electronics Supplies',
                'location' => 'Electronics Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Keyboard Wrist Rest',
                'description' => 'Ergonomic keyboard wrist rest',
                'category' => 'computer',
                'unit' => 'pcs',
                'sku' => 'WRIST-REST-KB',
                'min_stock' => 5,
                'current_stock' => 8,
                'cost_price' => 4.00,
                'selling_price' => 8.00,
                'supplier' => 'Ergonomics Co.',
                'location' => 'Electronics Cabinet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Mailing Supplies
            [
                'name' => 'Shipping Envelopes',
                'description' => 'Bubble mailer shipping envelopes',
                'category' => 'mailing',
                'unit' => 'packs',
                'sku' => 'ENV-SHIP-BUBBLE',
                'min_stock' => 5,
                'current_stock' => 15,
                'cost_price' => 12.00,
                'selling_price' => 20.00,
                'supplier' => 'Shipping Supplies Ltd.',
                'location' => 'Mail Room',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Packing Tape',
                'description' => 'Clear packing tape 2-inch',
                'category' => 'mailing',
                'unit' => 'rolls',
                'sku' => 'TAPE-PACK-2IN',
                'min_stock' => 8,
                'current_stock' => 18,
                'cost_price' => 2.00,
                'selling_price' => 4.00,
                'supplier' => 'Shipping Supplies Ltd.',
                'location' => 'Mail Room',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Cleaning Supplies
            [
                'name' => 'Monitor Wipes',
                'description' => 'Anti-static monitor cleaning wipes',
                'category' => 'cleaning',
                'unit' => 'packs',
                'sku' => 'WIPES-MONITOR',
                'min_stock' => 6,
                'current_stock' => 12,
                'cost_price' => 3.50,
                'selling_price' => 7.00,
                'supplier' => 'Cleaning Supplies Co.',
                'location' => 'Janitorial Closet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Keyboard Cleaner',
                'description' => 'Compressed air for keyboard cleaning',
                'category' => 'cleaning',
                'unit' => 'bottles',
                'sku' => 'CLEANER-KEYBOARD',
                'min_stock' => 4,
                'current_stock' => 9,
                'cost_price' => 4.00,
                'selling_price' => 8.00,
                'supplier' => 'Cleaning Supplies Co.',
                'location' => 'Janitorial Closet',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Other Items
            [
                'name' => 'First Aid Kit Small',
                'description' => 'Small office first aid kit',
                'category' => 'other',
                'unit' => 'boxes',
                'sku' => 'FIRSTAID-SMALL',
                'min_stock' => 2,
                'current_stock' => 5,
                'cost_price' => 15.00,
                'selling_price' => 25.00,
                'supplier' => 'Safety Supplies Inc.',
                'location' => 'Emergency Supplies',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Whiteboard Eraser',
                'description' => 'Standard whiteboard eraser',
                'category' => 'other',
                'unit' => 'pcs',
                'sku' => 'ERASER-WHITEBOARD',
                'min_stock' => 6,
                'current_stock' => 10,
                'cost_price' => 1.50,
                'selling_price' => 3.00,
                'supplier' => 'Presentation Supplies Inc.',
                'location' => 'Meeting Room Storage',
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert all items
        DB::table('stationary_items')->insert($items);

        $this->command->info('Successfully seeded 30 stationary items for office use.');
    }
}
