services:
    art-fad-app:
        build:
            context: .
            dockerfile: docker/DockerFile
        image: fad-app:latest
        container_name: "art-fad-app"
        platform: linux/amd64
        networks:
            - app-network
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 5175:5175
        volumes:
            - ".:/var/www/html"
            - "./docker/php.ini:/usr/local/etc/php/conf.d/php.ini"
    nginx:
        image: nginx:alpine
        container_name: art-fad-nginx
        platform: linux/amd64
        restart: unless-stopped
        ports:
            - 8002:80
        working_dir: "/var/www/html"
        volumes:
            - ".:/var/www/html"
            - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
        networks:
            - app-network
        depends_on:
            - art-fad-app
    mariadb:
        image: mariadb:11.8.2
        container_name: art-fad-mariadb
        platform: linux/amd64
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
            MARIADB_DATABASE: "${DB_DATABASE}"
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
        ports:
            - 3308:3306
        volumes:
            - "vol-art-fad-mariadb:/var/lib/mysql"
        networks:
            - app-network
    redis:
        image: redis:8.0-alpine
        container_name: art-fad-redis
        platform: linux/amd64
        restart: unless-stopped
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "6384:6379"
        networks:
            - app-network
    mailhog:
        image: mailhog/mailhog:latest
        container_name: art-fad-mailhog
        platform: linux/amd64
        ports:
            - 1027:1025
            - 8027:8025
        networks:
            - app-network
    
networks:
    app-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.105.0/24
volumes:
    vol-art-fad-mariadb:
        driver: local